<LocationPageLayout>:
    orientation: "vertical"
    spacing: 10

    BoxLayout:
        size_hint_y: None
        height = 50
        Label:
            text: "Enter a Location"
            bold: True 
            size_hint_x: 0.90
        Button:
            text: "X"
            bold: True
            size_hint_x 0.10

    BoxLayout:
        orientation = "vertical"
        TextInput:
            hint_text: "Location"
    Button:
        text="Search"

        